# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import system_backend_pb2 as proto_dot_system__backend__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/system_backend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommenderServiceStub(object):
    """Service definition for the Recommender System
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/system_backend.RecommenderService/Search',
                request_serializer=proto_dot_system__backend__pb2.SearchRequest.SerializeToString,
                response_deserializer=proto_dot_system__backend__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetArticleInfo = channel.unary_unary(
                '/system_backend.RecommenderService/GetArticleInfo',
                request_serializer=proto_dot_system__backend__pb2.GetArticleInfoRequest.SerializeToString,
                response_deserializer=proto_dot_system__backend__pb2.GetArticleInfoResponse.FromString,
                _registered_method=True)
        self.GetArticleFull = channel.unary_unary(
                '/system_backend.RecommenderService/GetArticleFull',
                request_serializer=proto_dot_system__backend__pb2.GetArticleFullRequest.SerializeToString,
                response_deserializer=proto_dot_system__backend__pb2.GetArticleFullResponse.FromString,
                _registered_method=True)


class RecommenderServiceServicer(object):
    """Service definition for the Recommender System
    """

    def Search(self, request, context):
        """Search for articles based on a term
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleInfo(self, request, context):
        """Get article information (name and description)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleFull(self, request, context):
        """Get full article information (name, description, and body)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=proto_dot_system__backend__pb2.SearchRequest.FromString,
                    response_serializer=proto_dot_system__backend__pb2.SearchResponse.SerializeToString,
            ),
            'GetArticleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleInfo,
                    request_deserializer=proto_dot_system__backend__pb2.GetArticleInfoRequest.FromString,
                    response_serializer=proto_dot_system__backend__pb2.GetArticleInfoResponse.SerializeToString,
            ),
            'GetArticleFull': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleFull,
                    request_deserializer=proto_dot_system__backend__pb2.GetArticleFullRequest.FromString,
                    response_serializer=proto_dot_system__backend__pb2.GetArticleFullResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'system_backend.RecommenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('system_backend.RecommenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommenderService(object):
    """Service definition for the Recommender System
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/system_backend.RecommenderService/Search',
            proto_dot_system__backend__pb2.SearchRequest.SerializeToString,
            proto_dot_system__backend__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/system_backend.RecommenderService/GetArticleInfo',
            proto_dot_system__backend__pb2.GetArticleInfoRequest.SerializeToString,
            proto_dot_system__backend__pb2.GetArticleInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticleFull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/system_backend.RecommenderService/GetArticleFull',
            proto_dot_system__backend__pb2.GetArticleFullRequest.SerializeToString,
            proto_dot_system__backend__pb2.GetArticleFullResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
