# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/system_backend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/system_backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/system_backend.proto\x12\x0esystem_backend\"9\n\rSearchRequest\x12\x13\n\x0bsearch_term\x18\x01 \x01(\t\x12\x13\n\x0bnum_results\x18\x02 \x01(\x05\"%\n\x0eSearchResponse\x12\x13\n\x0b\x61rticle_ids\x18\x01 \x03(\x05\"+\n\x15GetArticleInfoRequest\x12\x12\n\narticle_id\x18\x01 \x01(\x05\";\n\x16GetArticleInfoResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"+\n\x15GetArticleFullRequest\x12\x12\n\narticle_id\x18\x01 \x01(\x05\"I\n\x16GetArticleFullResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t2\x9f\x02\n\x12RecommenderService\x12G\n\x06Search\x12\x1d.system_backend.SearchRequest\x1a\x1e.system_backend.SearchResponse\x12_\n\x0eGetArticleInfo\x12%.system_backend.GetArticleInfoRequest\x1a&.system_backend.GetArticleInfoResponse\x12_\n\x0eGetArticleFull\x12%.system_backend.GetArticleFullRequest\x1a&.system_backend.GetArticleFullResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.system_backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=46
  _globals['_SEARCHREQUEST']._serialized_end=103
  _globals['_SEARCHRESPONSE']._serialized_start=105
  _globals['_SEARCHRESPONSE']._serialized_end=142
  _globals['_GETARTICLEINFOREQUEST']._serialized_start=144
  _globals['_GETARTICLEINFOREQUEST']._serialized_end=187
  _globals['_GETARTICLEINFORESPONSE']._serialized_start=189
  _globals['_GETARTICLEINFORESPONSE']._serialized_end=248
  _globals['_GETARTICLEFULLREQUEST']._serialized_start=250
  _globals['_GETARTICLEFULLREQUEST']._serialized_end=293
  _globals['_GETARTICLEFULLRESPONSE']._serialized_start=295
  _globals['_GETARTICLEFULLRESPONSE']._serialized_end=368
  _globals['_RECOMMENDERSERVICE']._serialized_start=371
  _globals['_RECOMMENDERSERVICE']._serialized_end=658
# @@protoc_insertion_point(module_scope)
