FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu && \
  pip install --no-cache-dir -r requirements.txt

COPY datasets/ datasets/
COPY proto/ proto/
COPY search.py search.py
COPY main.py main.py

EXPOSE 50051
CMD ["python", "main.py"]
